### ISSUE TITLE
React 15.6.2 Umbrella

### ISSUE THREAD

**Issue by aweary** [facebook/react#10040]
This is an umbrella issue for fixes that need to be included in the next 15.6 patch release, which should be 15.6.2.

## Commits

- [x] https://github.com/facebook/react/issues/10030 - ChangeEventPlugin.js IE detection is broken on Chrome/Safari/FF etc (PR https://github.com/facebook/react/issues/10032)
- [ ] No error when element with ref created in another elements constructor in dev environment. (PR https://github.com/facebook/react/pull/10025) https://github.com/facebook/react/issues/9635
- [x] Treat columns property as a unitless number #10115
- [x] move augmentClass definition above SyntheticEvent Proxy replacement #10011
- [x] Use a closure to bind argument to callback in ReactErrorUtils #8363
- [x] Fix uncontrolled radios #10156
- [x] Add controlList to DOM property whitelist #9940

## Documentation

- [ ] Changelog 
- [ ] Documentation

## Misc

- [ ] Update lockfile
- [ ] Version bump
- [ ] Bower

**Comment by gaearon** [comment]
https://github.com/facebook/react/issues/10125

**Comment by nhunzaker** [comment]
Is it too late to squeeze in https://github.com/facebook/react/commit/331ef3ec913f867159b6178ef35f8a0b4472ab4f?

Related issue: https://github.com/facebook/react/issues/9594#issuecomment-314831171

**Comment by gaearon** [comment]
Sounds good. This list keeps growing because we're not actively working on that release.

**Comment by nhunzaker** [comment]
Added https://github.com/facebook/react/pull/9940 (controlList field) to the list

**Comment by frenchie4111** [comment]
#10030 is causing me issues. Any idea when this version will go out?

**Comment by jquense** [comment]
https://github.com/facebook/react/pull/10186 as well

**Comment by nhunzaker** [comment]
Ah @frenchie4111 this is on me. I'll start preparing a release. 

@aweary or @flarnie, is there any documentation preparing a release? Otherwise, I'll do my best to copy your prior releases and take notes :)

**Comment by gaearon** [comment]
There is documentation [here](https://github.com/facebook/react/blob/master/scripts/release-manager/Readme.md). But it's not very relevant because we're not using Release Manager for 15.x branch anymore. It has diverged too much. So the goal is to cherry pick as little as possible.

**Comment by gaearon** [comment]
It's still a good idea to walk through the document (without doing the Release Manager related bits).

**Comment by colebowl** [comment]
Hi @gaearon / @nhunzaker - Is there any update on this release? We are waiting on the fix for #10156 to be released to resolve some issues we are facing. Thanks!

**Comment by nhunzaker** [comment]
@colebowl I am sorry to test your patience. I got pretty nuked by some custom attribute stuff for 16.x. I'll begin preparing the 15.6.2 release _right now_, over lunch.

**Comment by colebowl** [comment]
@nhunzaker  - No apologies necessary, thanks a million for getting on this for us! Let me know if I can help!

**Comment by nhunzaker** [comment]
Did we ever come to a conclusion on https://github.com/facebook/react/pull/10025?

**Comment by mergebandit** [comment]
Also not being snarky - just not sure what "preparing the release _right now_" translates to in terms of release dates.

**Comment by SharanyaRam** [comment]
Hello, 

Any idea when 15.6.2 will be released? I'm waiting for the controlList attribute in video tag. 

Thanks!

**Comment by frenchie4111** [comment]
Any more updates on this?

**Comment by mukundgoel** [comment]
Was still waiting on https://github.com/facebook/react/issues/10040.. If you guys can give an upate that will be much appreciated. :)

**Comment by MichaelDeBoey** [comment]
It seems like @sophiebits already published `v15.6.2`, but it didn't get into master yet I think...

**Comment by MichaelDeBoey** [comment]
It seems like @sophiebits already published `v15.6.2`, but it didn't get into master yet I think...

**Comment by nhunzaker** [comment]
Yep! @sophiebits sent out 15.6.2 with these changes and the new license last night. We should be good to go here:
https://facebook.github.io/react/blog/2017/09/25/react-v15.6.2.html

**Comment by aweary** [comment]
@nhunzaker thanks for managing this release 🙌
