### ISSUE TITLE
Release checklist for 16 RC

### ISSUE THREAD

**Issue by flarnie** [facebook/react#10623]
#### Ensure all commits in master were tested at Facebook.

* Check that they were a part of the latest internal sync.
* For stable releases, prefer that they’ve been landed for a week or so.
* Only skip this step if you really know what you’re doing!

#### Verify that you have npm permissions.

- [x] You’re in `npm owner ls react`
- [x] You’re in `npm owner ls react-art`
- [x] You’re in `npm owner ls react-dom`
- [x] You’re in `npm owner ls react-test-renderer`
- If not, ping someone on the team!

#### Ensure your React is fresh.

- [x] Ensure you’re on `master`
- [x] Do a `git pull`
- [x] Is master green on CI? Check [the most recent commits](https://github.com/facebook/react/commits/master).
- [x] Check that your local `git log` output matches the commit list.
- [x] Run `yarn` in the repo root.

#### Ensure runtime dependencies match what users would get.

- [x] For `fbjs`:
  - [x] Look at the version range of `fbjs` in root `package.json`.
  - [x] Ensure all `packages/*/package.json` depending on `fbjs` specify the same range.
  - [x] Run `yarn upgrade fbjs@^THAT_VERSION` in the repo root. (Don’t miss the caret!)
- [x] For `object-assign`:
  - [x] Look at the version range of `object-assign` in root `package.json`.
  - [x] Ensure all `packages/*/package.json` depending on `object-assign` specify the same range.
  - [x] Run `yarn upgrade object-assign@^THAT_VERSION` in the repo root. (Don’t miss the caret!)
- [x] For `prop-types`:
  - [x] Look at the version range of `prop-types` in root `package.json`.
  - [x] Ensure all `packages/*/package.json` depending on `prop-types` specify the same range.
  - [x] Run `yarn upgrade prop-types@^THAT_VERSION` in the repo root. (Don’t miss the caret!)
- [x] This might change the lockfile. This **should not** change any `package.json`.
- [x] Commit the changes, if any. (see https://github.com/facebook/react/pull/10626)

- [x] **Edit:** `react-art` is broken in the 16 branch but this shouldn't block RC, and will be fixed asap by @sophiebits and @flarnie in #10629

#### Do the local sanity checks in the repo root.

- [x] Run `yarn test` in the repo root.
- [x] Run `yarn lint` in the repo root.
- [x] Run `yarn flow` in the repo root.

#### _STABLE RELEASE ONLY:_ Update error codes.

- [x] Run `yarn build -- --extract-errors` in the repo root.
- [x] If `scripts/error-codes/codes.json` changes, `git commit -am 'Update error codes'`
- [x] **Maybe:** If we still have a separate `*-stable` branch for docs when you’re reading this, we need to cherry-pick that commit to that branch. This makes sure the website decoder knows about the updated error codes. But ideally we should just change docs to serve from master.

(See https://github.com/facebook/react/pull/10619 https://github.com/facebook/react/pull/10621 and https://github.com/facebook/react/pull/10622)

#### Update the version.

- [x] Update export in `src/ReactVersion.js`
- [x] Update `version` in all `packages/*/package.json`:
  - [x] `packages/react-art/package.json`
  - [x] `packages/react-dom/package.json`
  - [x] `packages/react-noop-renderer/package.json`
  - [x] `packages/react-test-renderer/package.json`
  - [x] If you see any other packages, update this list :-)
- [x] Run `yarn version-check` to verify your changes.
- [x] `git commit -am "<version number>"`

#### Build it!

- [x] Run `yarn build` in the repo root.

#### Run fast packaging smoke test.

- [x] Open `fixtures/packaging/babel-standalone/dev.html` in the browser for a smoke test.
- [x] It should say “Hello world!”

#### Run slow packaging smoke test.

- [x] Go to `cd fixtures/packaging` and run `node build-all.js`
- [x] `npm install -g serve`
- [x] Go to the repo root and run `serve -s .`
- [x] Open http://localhost:5000/fixtures/packaging/ and verify every iframe shows “Hello World!”

#### Release!

- [x] Run `git push`
- [x] Run `git push --tags`
- [x] Go to `build/packages`
  - [x] For every subfolder:
    - [x] **For non-stable versions:** Run `npm publish --tag next` in the subfolder.
    - [x] **For stable versions:** Run `npm publish` in the subfolder.

#### _Bonus:_ Try it out!

- [ ] `create-react-app myapp`
- [ ] `cd myapp`
- [ ] `npm start`

**Comment by flarnie** [comment]
🎉 w00t~
