### ISSUE TITLE
React 16 Known Regressions

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11065]
Going to track them here since website issues are creating a lot of noise.

### Fixed in Master

- [x] https://github.com/facebook/react/issues/10909 Extra variable in UMDs, fixed in https://github.com/facebook/react/pull/10935
- [x] https://github.com/facebook/react/issues/10831 `null` instead of component stack in a warning, fixed in https://github.com/facebook/react/pull/10915
- [x] https://github.com/facebook/react/issues/10865 Crash when hydrating on IE11 in development, fixed in https://github.com/facebook/react/pull/10921
- [x] https://github.com/facebook/react/issues/10987 `tabIndex` getting lost on SVG, fixed in https://github.com/facebook/react/pull/11033
- [x] https://github.com/facebook/react/issues/11017 Crash rendering into shadow root, fixed in https://github.com/facebook/react/pull/11037
- [x] https://github.com/facebook/react/issues/10938 We should allow running test and shallow renderers in production again, fixed in https://github.com/facebook/react/pull/11112.
- [x] https://github.com/facebook/react/issues/10598 SSR doesn't separate unrelated text nodes in some cases, fixed in https://github.com/facebook/react/pull/11109.
- [x] https://github.com/facebook/react/issues/11103 SSR: ReactDOM client and server handling newlines differently causing mismatch warnings, fixed in https://github.com/facebook/react/pull/11119.
- [x] https://github.com/facebook/react/pull/11156 Peer dependencies warn for beta?
- [x] https://github.com/facebook/react/issues/10906 `onMouseEnter` fires twice after a child is added, fixed in https://github.com/facebook/react/pull/11164.
- [x] https://github.com/facebook/react/issues/11152 `onMouseEnter` fires when hovered over a child, fixed in https://github.com/facebook/react/pull/11164.
- [x] https://github.com/facebook/react/issues/11161 Shallow renderer doesn’t merge multiple `setState()` calls in `componentWillMount` correctly, fixed in https://github.com/facebook/react/pull/11167.
- [x] SSR throws an obscure error on bad `style` prop, fixed in https://github.com/facebook/react/pull/11173.
- [x] https://github.com/facebook/react/issues/11172 IE11 loses textarea placeholder on first render, fixed in https://github.com/facebook/react/pull/11177.
- [x] https://github.com/facebook/react/issues/10772 False positive warning when rehydrating camel-case SVG tag names, fixed in https://github.com/facebook/react/pull/11174.
- [x] https://github.com/facebook/react/issues/10993 False positive warning when rehydrating `<noscript>`, fixed in https://github.com/facebook/react/pull/11157.
- [x] https://github.com/facebook/react/issues/11159 `autoFocus` doesn't work with SSR.

### New Features Added in Master
- [x] Allow `on` attribute (but not other `on...` attributes). https://github.com/facebook/react/pull/11153
- [x] Allow explicitly shallow ignore of hydration warning. https://github.com/facebook/react/pull/11126

**Comment by ptomasroos** [comment]
Would it be possible to get a updated next on npm for the react 16 regressions that been fixed?

**Comment by iamdustan** [comment]
@ptomasroos 16.1 will be releaed in the not-too-distant future.

**Comment by ptomasroos** [comment]
Thanks for the feedback @iamdustan

**Comment by gaearon** [comment]
We’ll release it within a week or two. The work on these problems is done so there’s no need to keep the issue open. I’ll lock because comments here won’t help get the release out faster. We need to test it more at Facebook first.

**Comment by gaearon** [comment]
React `16.1.0-beta` has been released. Please update `react`, `react-dom`, and `react-test-renderer` (if you use it) to this version and let us know if it solved the issue! We’d appreciate if you could test before Monday when we plan to get `16.1.0` out.
