### ISSUE TITLE
Improving Browser QA

### ISSUE THREAD

**Issue by nhunzaker** [facebook/react#11079]
We manually test a lot of behavior that can not be captured by JSDOM. Change events, number input quirks, event pooling, error handling, etc.

Despite this test suite, comprehensive unit tests, alpha, beta, and release candidates, a number of bugs have slipped through. Particularly around change events.

I want to explore what it would look like to reduce the burden of manual browser QA when possible. Particularly around things like change events, which hook into JavaScript DOM APIs and should be automatable.

I've filed this issue for myself to explore the following areas (though I'd be happy for others to pitch in 😄):

- [ ] Deploying the [DOM Test Fixtures](https://github.com/facebook/react/tree/master/fixtures/dom) to a public URL to distribute manual QA and run automated tests against it
- [ ] Investigate [BrowserStack](https://browserstack.com) or [Sauce Labs](https://saucelabs.com) as possible browser automation options
- [ ] Deploy a nightly or edge build of React with an accompanying JSFiddle to make it easier to determine if a fix works on master without needing to know how to setup React locally.
- [ ] With automation in place, what extremely laborious (but comprehensive) tests could we run to help fight regressions?

---

I'm probably missing something, but this is where I'm going to start. I'll post follow-up comments as I learn stuff.

**Comment by nhunzaker** [comment]
cc @aweary and @jquense

**Comment by aweary** [comment]
* Deploying a build of the fixutres for PRs would be really helpful. We (inadvertently) already have this feature with the docs site, so it should be possible 😀

* It would be nice if the fixtures app had JSFiddle like functionality. That way we could quickly test out DOM changes locally without having to write a new test case.

> Deploy a nightly or edge build of React with an accompanying JSFiddle to make it easier to determine if a fix works on master without needing to know how to setup React locally

@zpao used to host a site that deployed builds from master, I'll try to find it when I get home.

**Comment by sophiebits** [comment]
http://react.zpao.com/ (still builds from our CI)

**Comment by gaearon** [comment]
I think @sophiebits also suggested having contractors run the QA tests in different browsers. Not sure how hard it would be.

**Comment by jquense** [comment]
I think that having a few, focused selenium tests via sauces labs or the like for particularly fraught areas is a a reasonable idea. Yes they can be flakey but if they can at least provide some canary-in-the-coalmine early warnings that can inform where to spend time doing some manual QA. The unit-test nature of these tests too should reduce the flakey-ness, plus we get some insight when we break peoples selenium workflows.

CircleCI's v2 workflows feature also makes it easier to set up flows that aren't required or need manual approval.

**Comment by jquense** [comment]
if it helps also i have some experience with saucelabs/browserstack I've found SL to be less flakey across browsers and done a bunch of e2e testing with protractor and react with better than expected results. glad to help out here :)

**Comment by aweary** [comment]
I also want to call back to https://github.com/facebook/react/issues/9301. If we have a definitive list of the browsers we _need_ to test in, we could make sure that we're not wasting time testing in unsupported browsers.

**Comment by nhunzaker** [comment]
I've started to work with [NightwatchJS](http://nightwatchjs.org/api/#commands) and [BrowserStack Automate](https://www.browserstack.com). It is very easy to run a test against all of the browsers we cover. 

This flow would involve:

1. Automated deployment to an integration URL whenever a pull request is sent out
2. A hook to expose that URL to a pull request
3. Run the automated tests against the URL, providing it as environment variable

Here's some code:
https://github.com/nhunzaker/nightwatch-test

I'm able to run an automated test in Safari, Chrome, Firefox, IE, and Edge. It's _pretty neat_. BrowserStack even records the test output.

<img width="1357" alt="screen shot 2017-11-30 at 8 49 02 am" src="https://user-images.githubusercontent.com/590904/33433864-5484ceac-d5ab-11e7-8db3-c77018d38340.png">

This isn't cheap though. **If we went this route, we would need an [Automate or Automate Mobile subscription](https://www.browserstack.com/accounts/subscriptions?tab=browser-plans-tab)**.  This is $1000-1500 for a yearly subscription.

Still. I think this a promising way to go. We could automate testing against ~30 browsers.

**Comment by jquense** [comment]
@nhunzaker that's awesome I was just thinking today i wanted to make some time to work on this. maybe can chat a bit on discord (or whatever)? I fairly recently hooked up selenium and e2e tests for a work app and have some thoughts and experiences that might be useful here, about which stack to use and browserstack vs saucelabs

**Comment by klamping** [comment]
I'd like to try helping out this cause. I still need to figure out what part I'd like to work on first, but I figure I'd start by saying hi here.

FYI, Sauce Labs offers a free plan for open-source projects, so you wouldn't need to worry about a monthly/yearly license. All you have to do is reach out to their customer support: https://saucelabs.com/open-source

On that note, Netlify is a static-site server (similar to github pages) and may be useful for hosting the fixtures pages. They also have a free open-source plan: https://www.netlify.com/open-source/

/cc @giltayar

**Comment by klamping** [comment]
@nhunzaker fyi, I copied your NightwatchJS example and modified it to use WebdriverIO. You can check it out here:
https://github.com/klamping/wdio-react-example

Benefits of WebdriverIO over NightwatchJS are that WebdriverIO provide built-in services to connect to tools like Browserstack or Chromedriver, and it also provides more flexibility in how you write your tests. 

Would love to get your thoughts on this direction, as I have some time to keep plugging away at writing some browser automation for the DOM fixtures.

**Comment by klamping** [comment]
So I've been doing some work on that test repo and wanted to provide a quick update.

First off, I changed the repo name so that it now lives here:
https://github.com/klamping/react-webdriverio-tests

I've also added a few more tests and plan on adding many more to come.

Using CircleCI and Zapier, it's "integrated" with the React PRs to run the tests I do have on the PR code and print out a report for each PR.

I have a temporary issues page which stores the links to the PR, report and CircleCI job. You can check it out here:
https://github.com/klamping/react-webdriverio-tests/issues/1

Right now, the tests are running in Firefox and Chrome on the CircleCI box. I'd love to get it integrated with BrowserStack or Sauce Labs, but don't have an account.

Any feedback or suggested direction would be much appreciated. I'm hoping this can help provide a good proof-of-concept (or even some real value) in to how automated browser testing works.

**Comment by christian-bromann** [comment]
@nhunzaker I am happy to power up your open source account at Sauce Labs for such beautiful open source projects like React 😉
