### ISSUE TITLE
Umbrella: React DOM Bugs

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11097]
Since I was going through all open issues yesterday and today, I also compiled a list of things that seem broken in ReactDOM, grouped by areas.

I don’t think all of these issues are equally important but I’d like to start a discussion around how we can start attacking them—both in shorter in longer term. For example any potential fixes to change event logic would need to take https://github.com/facebook/react/issues/9657 into account (or even inform it).

I think it would be a good topic for our next chat, cc @jquense @aweary @nhunzaker. Maybe we could also broadcast it this time? 😃  

## Autofill

* [ ] https://github.com/facebook/react/issues/1159 Provide a way to handle browser-autocompleted form values on controlled components
* [ ] https://github.com/facebook/react/issues/2585 Handle browser autofill gracefully when server-side rendering
* [ ] https://github.com/facebook/react/issues/7328 IE 11 and Edge no longer prompt to remember password on controlled form
* [ ] https://github.com/facebook/react/issues/10468 DOM Fixture Form Coverage: Restored State and Auto-fill 

## Composition Events

* [ ] https://github.com/facebook/react/issues/3926 Change event fires too many times when inputing Chinese characters
* [ ] https://github.com/facebook/react/issues/10217 Incorrect data in compositionend event when typing Korean on IE11
* [ ] https://github.com/facebook/react/issues/8683 Composition Events(Chinese, Japanese IME) problem in controlled components(input, textarea)
* [ ] https://github.com/facebook/react/issues/8423 onChange does not work well with IE11 at Japanese IME. in React 15.4.0

## Mouse Enter / Leave

* [ ] https://github.com/facebook/react/issues/4251 mouseenter fires on disabled inputs whereas mouseleave does not
* [ ] https://github.com/facebook/react/issues/10109 Mouseenter event not triggered when cursor moves from disabled button
* [ ] https://github.com/facebook/react/issues/5739 MouseEnter event bubbling
* [ ] https://github.com/facebook/react/issues/7135 onMouseEnter propagation in double reactroot
* [ ] https://github.com/facebook/react/issues/6807 onMouseLeave not working as expected

# Input, Checkbox, and Select

* [ ] https://github.com/facebook/react/issues/4672 Change event does not fire in IE and Edge under certain circumstances
* [ ] https://github.com/facebook/react/issues/4854 Pressing spacebar on a checked radio button only fires click in some browsers
* [ ] https://github.com/facebook/react/issues/6368 Input type 'email' as controlled component does not control white spaces
* [ ] https://github.com/facebook/react/issues/6951 Changing state in onFocus and onChange for a select multiple element does not work in Firefox
* [ ] https://github.com/facebook/react/issues/7024 select onChange not firing when using keyboard
* [ ] https://github.com/facebook/react/issues/7281 Input onChange not triggered every time in IE11 if e.preventDefault() used
* [ ] https://github.com/facebook/react/issues/7489 input element `setSelectionRange` after backspace does not work in IE10
* [ ] https://github.com/facebook/react/issues/7630 Radio buttons are not correctly checked when using multiple lists of radio buttons
* [ ] https://github.com/facebook/react/issues/7769 input autoFocus causes focus to be emitted before ref
* [ ] https://github.com/facebook/react/issues/8514 Undo behavior in controlled textareas works differently from the default behaviour in chrome
* [ ] https://github.com/facebook/react/issues/8531 IE10 triggers onChange twice when replacing a text selection 
* [ ] https://github.com/facebook/react/issues/8642 textarea + onFocus + stopPropagation = incorrect cursor rendering on Firefox
* [ ] https://github.com/facebook/react/issues/8876 onBeforeInput fires after Edge updates the DOM
* [ ] https://github.com/facebook/react/issues/8938 Clear button on iOS date input does not return correct event value 
* [ ] https://github.com/facebook/react/issues/9023 event.preventDefault in click handler does not prevent onChange from being called 
* [ ] https://github.com/facebook/react/issues/11010 Reset of select ignores defaultValue

**Comment by landvibe** [comment]
[This PR](https://github.com/facebook/react/pull/11227) fixed #7630

**Comment by sw-yx** [comment]
would love to listen in on this chat and how you discuss things!

**Comment by nhunzaker** [comment]
https://github.com/facebook/react/pull/11534 fixes #7328 (IE 11 and Edge no longer prompt to remember password on controlled form)

**Comment by moe091** [comment]
I'm working on [#7769](https://github.com/facebook/react/issues/7769l), will tackle others when done
