### ISSUE TITLE
Release script follow-up

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11481]
- [X] #11482: Add a timeout before querying npm right after publish
- [X] #11482: Conditionally log some post publish steps
- [X] #11482: Maybe print ready-to-paste `yarn add ...` instructions for CRA prerelease testing
- [ ] #11504: Publish all packages that aren't `private` and remove the whitelist in config
- [ ] #11504: Add "v" prefix for release tags
- [ ] #11504: Nit: seconds => minutes for long tasks 😉

**Comment by bvaughn** [comment]
> Nit: seconds => minutes for long tasks 😉

😆
