### ISSUE TITLE
Fabric Todos

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#12073]
For my own notes here are some spill-overs from the Fabric renderer commit.

- [ ] Update currentProps for updates in the commit phase. Needs a host effect to be marked and we need a hook to do host updates in the persistent mode.
- [x] Actually use currentProps when extracting events in the component tree.
- [ ] Resuming will need to be able to not reuse host nodes used by another thread.
- [ ] Should always clone direct siblings of a changed node, in case they will relayout.

**Comment by gaearon** [comment]
What's still relevant? The point about resuming? Should we add it to general resuming umbrella in #13306?

**Comment by sebmarkbage** [comment]
It doesn't have to block resuming so I don't think so.
