### ISSUE TITLE
React 16.3.1 Umbrella

### ISSUE THREAD

**Issue by gaearon** [facebook/react#12509]
- [x] IE11 Fragment false positive warning fix (https://github.com/facebook/react/issues/12500, fixed in https://github.com/facebook/react/pull/12504)
- [x] Big DEV mode performance regression (https://github.com/facebook/react/issues/12502, fixed in https://github.com/facebook/react/pull/12510)
- [x] Error handling bugs related to replaying (https://github.com/facebook/react/issues/12449, fixed in https://github.com/facebook/react/pull/12508)

**Comment by blling** [comment]
Should close this, 16.3.1 has released:)
