### ISSUE TITLE
[meta] Bringing Flow types in line with 16.3 APIs

### ISSUE THREAD

**Issue by billyjanitsch** [facebook/react#12553]
Hi!

I realize that the React team doesn't work on Flow directly, and that the React typings live there. However, there are currently some large gaps in Flow support for the new 16.2/16.3 APIs, and I thought it might be good to raise/track them here, for the benefit of people searching the React tracker.

I filed issues in the Flow repo for missing typings that didn't have outstanding PRs.

- [x] `UNSAFE_`-prefixed lifecycles (commit: https://github.com/facebook/flow/commit/cd8fdcdd8719ca0138fb71d30a786d70e98f136c)
- [x] `createContext` (commit: https://github.com/facebook/flow/commit/dd27ebbd14782cc103632e5459e106559d8b5511)
- [x] `createRef` (commits: https://github.com/facebook/flow/commit/dd27ebbd14782cc103632e5459e106559d8b5511, https://github.com/facebook/flow/commit/d74ab13a8dfc5395ec5883aa2fa56be0a03a3a3f)
- [x] `componentDidCatch` (PR: https://github.com/facebook/flow/pull/6044)
- [x] `forwardRef` (PR: https://github.com/facebook/flow/pull/6510)
- [ ] `getDerivedStateFromProps` (PR: https://github.com/facebook/flow/pull/6511)
- [ ] `getSnapshotBeforeUpdate` (PR: https://github.com/facebook/flow/pull/6511)
- [x] `StrictMode` (PR: https://github.com/facebook/flow/pull/6078)

Feel free to close this issue if you don't think it's useful. But maybe the React team knows someone on the Flow team who can help give priority to these libdef updates (especially those with PRs)?

❤️

**Comment by Kovensky** [comment]
I am curious to see how/if Flow will deal with `getDerivedStateFromProps`. It's not currently possible to safely type it in TypeScript's definition because `static` methods are not allowed to reference instance generic parameters.

```ts
class Component<P, S> {
  // this is a compile error because P/S are per-instance types from the POV of the compiler
  static getDerivedStateFromProps (props: P, nextState: S): Partial<S>|null
}
```

**Comment by gaearon** [comment]
In Flow, it's defined as

```js
  static getDerivedStateFromProps(
    nextProps: Props,
    prevState: State
  ): $Shape<State> | null {
    // ...
  }
```

**Comment by mrkev** [comment]
Three of the ones missing are issues without a PR. Is there anything blocking a PR? If not, feel free to make one and ping me to try and merge 👍

**Comment by motiz88** [comment]
Also opened facebook/flow#6511 to close facebook/flow#6101 (`getDerivedStateFromProps`) and facebook/flow#6104 (`getSnapshotBeforeUpdate`).

**Comment by rickyp-uber** [comment]
Are there any goals for the React library to own it's own definition types (e.g. move the definitions into this project)?
Question requested here: https://github.com/facebook/flow/issues/5474#issuecomment-420497117

**Comment by gaearon** [comment]
My understanding is that in many cases any typing changes to React also require some changes to Flow source (due to how React features are modeled) so I'm not sure it would actually fix anything except adding more friction to deploying these changes.

**Comment by rickyp-uber** [comment]
Agreed about the current state of the definition but to answer this specific question let's assume we can write the entire React flow definition in a *.js.flow file... would the React team be willing to host this in their own code base or do they want the Flow team to own it in their code base?

**Comment by gaearon** [comment]
How would release cycle work?

**Comment by rickyp-uber** [comment]
How do you mean? Since the *.js.flow file is within the React library, it gets released whenever the npm package is published. It's on the React team to make sure the definitions defined in the *.js.flow file are inline with the package's contents.

From a consumer standpoint, Flow reads the *.js.flow in the npm package installed and get's the types. If the npm package's API changes, the *.js.flow within that package should reflect it so when the consumer updates to the newer version, Flow should yell about the break. This actually ends up being easier and safer on the consumer because if they are using an older version of React, say 16, and flow-bin has definitions for React 18, the static type definitions may not be correct and could result in runtime failures.

Annoyingly, Flow doesn't have this [documented](https://flow.org/en/docs/libdefs/creation/#declaring-a-module-) on their website currently and clicking the link shoots off an alert that says "TODO". Overall though this is a similar design as typescript's definition files where for typescript's case instead of having an extra file at the root of the project, they have the definition location [defined in the package.json](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html).

**Comment by gaearon** [comment]
>If the npm package's API changes, the *.js.flow within that package should reflect it so when the consumer updates to the newer version, Flow should yell about the break. 

What if Flow itself makes a breaking change? Is the expectation that `.flow.js` that ships React is only guaranteed to work with latest Flow? Or that it's backwards compatible even if that results in a worse definition?

**Comment by rickyp-uber** [comment]
I think in general it's that the *.flow.js would generally only work with the latest version of flow. It would be on the consumer when they update the package to also update their version of flow if flow does fire an error.

**Comment by jbrown215** [comment]
forwardRef landed in https://github.com/facebook/flow/commit/9a3377aed70a1059fa0b8b28598cb465d080644c

**Comment by mrkev** [comment]
bump
