### ISSUE TITLE
"schedule" package umbrella

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#13559]
### Short term
- [ ] Replace the [`__getInteractionsRef` and `__getSubscriberRef` methods](https://github.com/facebook/react/blob/fb88fd9d8c9f72b8e2e7e1ae89652d2a6a707562/packages/schedule/src/Tracking.js#L84-L90) with direct, mutable exports (`__interactions` and `__subscriber`) and [update the `ScheduleTracking` UMD fork](https://github.com/facebook/react/blob/master/packages/shared/forks/ScheduleTracking.umd.js).
- [ ] Remove `__getInteractionsRef` and `__getSubscriberRef` from the `schedule/tracking` UMD [dev](https://github.com/facebook/react/blob/master/packages/schedule/npm/umd/schedule-tracking.development.js) and [prod](https://github.com/facebook/react/blob/master/packages/schedule/npm/umd/schedule-tracking.production.min.js) bundles since it's not part of the public API.

### Long term
- [ ] Move `schedule` to is own package (maybe even its own org) prior to a 1.0 release.
- [ ] Enable it to be used without a build step by replacing the dev/prod check with a single export.
- [ ] Add an ES module entry point as well as the CJS and UMD entry points

**Comment by bvaughn** [comment]
Type: Umbrella, ella, ella, eh, eh

**Comment by janryWang** [comment]
I would like to ask when can I officially release it?

**Comment by bvaughn** [comment]
We don't know a release date yet, sorry.

**Comment by janryWang** [comment]
Okay thanks.
