### ISSUE TITLE
Ship 0.11.1

### ISSUE THREAD

**Issue by zpao** [facebook/react#1915]
Here's what needs to be cherry-picked:
- [x] #1869 - 495d866a66d856d599fc79613ff488b60fd2e0b4
- [x] #1870 - 54d91c293d39ea82a84f7c9ed4e492ff6c72a811
- [x] #1908 (aka #1870 cleanup) - 6259d88f0352f0ab4388412122d5c911a6fb9329
- [x] #1879 - 6f0db657773656867cb2b9eabc85a4e12abebe9c
- [x] #1865 - 030071dd8b1eedb796747e51faaaa2b05e9e3c2d
- [x] #1903 - 8a135c0e75cfc3dfaba26deb49c8d85f12fa294b
- [x] #1876 - e8efa2a1e915da7aab90f6ad2ffcb226b7016293

And then other activities:
- [x] Update 0.11 changelog/blog post to mention descriptors (see 0.10), change in proptypes validation
- [x] Blog post (also refer to missed items in 0.11 blog), changelog for 0.11.1
- [x] everything else
