### ISSUE TITLE
[DevTools] Scheduling Profiler umbrella task

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#21866]
The [Scheduling Profiler](https://github.com/facebook/react/tree/main/packages/react-devtools-scheduling-profiler) is currently only accessible at [react-scheduling-profiler.vercel.app](https://react-scheduling-profiler.vercel.app/) and very few people know about it. Furthermore, the User Timing API marks that power this profiler are only enabled in the experimental release channel, which almost no one uses. We believe this profiler is an important part of understanding React’s concurrent scheduling and app performance.

### Initial release
 - [x] #21867: Enable the `enableSchedulingProfiler` flag for all _profiling_ builds (not just in the _experimental_ release channel).
 - [x] #21897: Embed the scheduling Profiler into the Chrome build of the React DevTools extension. (The profiler currently only supports User Timing marks extracted from Chrome’s profiling format.) Add this profiler as a new tab within the ⚛️ Profiler panel.
 - [x] #21897: Design a splash page with instructions on how to record and import data.
 - [x] #21897: Hide the "copy component stack" context menu item if the data doesn't contain a component stack.
 - [x] #21947: Expose events (e.g. mouse click events) in the timeline as well for context
 - [x] #21966: Stack native events vertically so they don't overlap.
 - [x] #21966: Highlight native event handlers that schedule sync/blocking render work.
 - [x] #21970: Custom cursor system for canvas to improve UX
 - [x] Hide commit snapshot selector when Scheduling Profiler tab is active.
 - [x] Maybe allow sections to be toggled/collapsed (e.g. native flame graph) and skip rendering?
- [x] #22043: Store imported profile data _and_ zoom/scroll state in new context (above scheduling profiler) so you don't lose it when you tab between profilers
 - [x] #22075: Fix `@reach/portal` bug unmount bug that gets thrown if you upload an invalid profile to the Scheduling profiler and then a valid profile afterward. ("_Uncaught Error: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node._")

### Follow up work
- [x] Create a discussion thread on the [React 18 Working Group](https://github.com/reactwg/react-18/discussions/) about it and gather usability feedback.
- [x] ~~Implement some sort of feature detection to hide this panel for `react-dom` builds that don't have `enableSchedulingProfiler` enabled? (Maybe only show it for v18+)~~ Probably not a good idea. You might want to import a profile on a non-React site.
- [ ] Follow ups from #22005 
  - [ ] Scroll state should be moved up into context
  - [ ] Time axis marks should remain fixed and not scroll off screen
  - [ ] Can we avoid having to explicitly call `surface.displayIfNeeded()` after an interaction (see https://github.com/facebook/react/pull/22005#issuecomment-896953399)
- [ ] Try coloring component rendering to match suspense colors for components that suspended. (May require updating the React profiler marks)
 - [ ] Revisit the concept of _batching_. It's currently defined as one or more renders followed by a potential commit (unless the render is explicitly cancelled). I think this doesn't properly take into account interleaved work (e.g. offscreen/idle pre-rendering). Batch ID should probably also take _lane(s)_ into consideration.

**Comment by bvaughn** [comment]
Note some prerequisite was done in #19892
