### ISSUE TITLE
Umbrella 0.13

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#2809]
- [x] refs - make them callbacks instead of first class (@spicyj / @sebmarkbage)
- [x] Move propType validation to element instead of class (@jsfb)
- [x] Warning if class.type is accessed (@sebmarkbage)
  - [ ] Clean up internal (@jsfb)
- [x] Expose React.Component base class (@sebmarkbage)
  - [x] Fix context (#2898)
- [x] Deprecate keyed objects as children with warning. (@jsfb / @sebmarkbage)
  - [x] Add ReactFragment API, expose as React.addons.fragment?
- [x] Fix ReactPerf
- [x] Change unmounted setState checks from invariant to warning (@zpao)
- [x] Add enqueueStateUpdate (name?) to enqueue updates that depend on this.state being consistent (since this._pendingState is gone). (@sebmarkbage)
- [x] fix devtools (@sebmarkbage)
- [x] do something about refs timing(#3128) (@sebmarkbage)
- [x] warn for `getDOMNode`, `isMounted` uses within `render` (#3171)
- [x] warn for Maps as children (#3171)
- [ ] `@providesModule react` (@zpao) (needs syncup with flow, internal)
- [ ] `--target` option for `jsx` (@zpao)

Won't fix:

- [ ] Expose DOM component refs as the actual DOM nodes. (Monkey patch props, setProps, getDOMNode onto it as an upgrade path.)
- [ ] Warnings on using a DOM Component's ref's getDOMNode or props
- [ ] Fix the error utils guard. See ReactCompositeComponentError-test
- [ ] Deprecate setProps? What's the alternative?
- [ ] expose cloneWithProps on React proper (not actual cloneWithProps but the other one)
- [ ] Deprecate replaceState?

**Comment by syranide** [comment]
@sebmarkbage `getDOMNode()` is not defined for `React.Component`, shouldn't it fall under "warn for one release and drop the next"?

**Comment by sebmarkbage** [comment]
@syranide No, because `React.Component` didn't exist in previously releases. Not exposing it explicitly to prevent new code from relying on it.

**Comment by syranide** [comment]
@sebmarkbage Makes sense, the problem I see with it is `this.refs.foobar.getDOMNode()` will now fail "arbitrarily", depending on whether the component moved away from `React.createClass` or not. I realize these are fairly rare circumstances, but it did bite me. I.e, it is not only the component itself that is affected, but the consumer of the component as well.

**Comment by sebmarkbage** [comment]
@syranide That's why we also have `React.findDOMNode(this.refs.foobar)` which moves the responsibility out of the instance itself into a global escape hatch.

**Comment by syranide** [comment]
@sebmarkbage Yeah definitely, what I'm saying is just this breaks the "first warn then break" approach React seems to generally take. Now, doing `npm update` and also getting an updated component could mean your app instantly breaks telling you to use `React.findDOMNode` rather than warning and also working as it should for now. But I personally don't mind, I've already fixed all call-sites... just saying :)

**Comment by sebmarkbage** [comment]
This scenario doesn't break because of `npm update` but because you're also adding a new component which is why I think it is fine. :)

**Comment by andreypopp** [comment]
@syranide those who maintain React components and upgrade from `React.createClass(...)` to ES6 classes should bump major version then. Probably a good thing to be noted in 0.13 release announcement.
