### ISSUE TITLE
Track upcoming DOM technology upgrades

### ISSUE THREAD

**Issue by jimfb** [facebook/react#2836]
- [x] Support hyphenated DOM components in JSX transform
- [ ] Usage from within an html import
- [x] Inserting components into a shadow DOM fragment (https://github.com/facebook/react/issues/840)
- [x] Arbitrary properties on DOM components
- [ ] Proper event handling
  - [ ] Events fired inside shadow DOM (https://discuss.atom.io/t/event-handling-with-the-shadow-dom-and-react/14580)
  - [ ] Custom events (https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events)
- [ ] Component prototype to provide change detection and execute a rerender.  We will want a component to be able to rerender, for instance, when the component's children (effectively treated as a prop in react) changes.  Detecting such changes will require a a default component implementation that does things like initialize a MutationObserver (https://dom.spec.whatwg.org/#mutationobserver).
- [ ] Potentially defer rendering until we're in the dom (as per https://github.com/facebook/react/issues/2398)
- [x] Remove tagName property (as per https://github.com/facebook/react/issues/2288)
- [ ] Support complex types as parameters to web components.  React components can take complex types, whereas dom nodes can only take in strings.  To pass a complex type to a web component, we'll need to run code at mount time that passes the additional parameters to the instantiated web component.
-  [ ] Stateful Imperative Bridge (as per https://github.com/facebook/react/issues/1711)

**Comment by nhunzaker** [comment]
@gaearon Just digging through some old issues to see if anything can be closed. 

Is there a way forward for an issue like this? 

Should this be moved to something like react-future?

**Comment by gaearon** [comment]
I think we can close this.

**Comment by jayarjo** [comment]
Where the custom events or anything along the line ever implemented in the React?

**Comment by GlitchedCode** [comment]
I tHiNk We CaN cLoSe ThIs
