### ISSUE TITLE
Ship 0.13

### ISSUE THREAD

**Issue by zpao** [facebook/react#3352]
- [x] make sure examples work (@zpao #3354)
- [x] docs
  - [x] `React.findDOMNode`
  - [x] `React.cloneElement` (@zpao #3363)
  - [x] `React.Component` (@sebmarkbage)
  - [x] ES6 class use
  - [x] Notes in component instance methods about what doesn't work in ES6 classes (@zpao)
  - [x] ~~Note in element.type~~ (no such documentation; mentioned change in blog; skipping)
  - [x] Update refs documentation for callback style (are we actually recommending this yet?) (@jsfb https://github.com/facebook/react/pull/3364)
  - [x] Update setState docs for function style(@jsfb)
  - [x] `React.addons.createFragment` (@spicyj #3353)
  - [x] `React.classSet` deprecation
  - [x] shallow testing (#2963)
- [ ] fb.me updates (@zpao)
  - [ ] http://fb.me/react-invariant-dangerously-set-inner-html → http://facebook.github.io/react/tips/dangerously-set-inner-html.html
  - [x] ~~http://fb.me/react-legacyfactory~~
  - [x] ~~http://fb.me/react-context-by-parent~~
  - [x] ~~http://fb.me/react-warning-keys~~
  - [x] ~~http://fb.me/react-transferpropsto~~
  - [x] ~~http://fb.me/react-addons-classset~~
  - [x] ~~http://fb.me/react-jsx-lower-case~~
- [x] ship it (blog, npm, bower, etc) (@zpao)
- [ ] update react-tutorial (@zpao https://github.com/reactjs/react-tutorial/pull/40)
- [x] ship jsx upgrade tool (@zpao)
- [x] update react-source gem (@zpao)
- [x] update react-rails gem? (@zpao)
- [x] ship React ART 0.13 (@zpao https://github.com/reactjs/react-art/pull/43)
- [x] update readme, etc in master
- [x] update fiddles

**Comment by camspiers** [comment]
Do we want to make sure the performance test suite still works (I had a look the other day and I think they are broken)?

**Comment by zpao** [comment]
Nah, not going to block on that. We can fix it independently.

**Comment by zpao** [comment]
RE: Update refs documentation for callback style
> are we actually recommending this yet?

Doesn't matter, we support it and talked about it in the changelog.

We can't have discussions inline in a text field, we don't get updates and I have no idea who asked. Ask them in comments.

**Comment by spicyj** [comment]
Sorry, me.

**Comment by zpao** [comment]
@camspiers Ah, I'm assuming you mean the testing suite and not `React.addons.Perf` (there was a problem but we believe that's all in shape now). Correct me if I was wrong though!

**Comment by zpao** [comment]
Apparently fb.me urls *can't* be changed (well, not without bypassing some checks which I'm not sure are safe to bypass) so we'll skip that part for now. Not the end of the day, but my bad.

**Comment by vipulnsward** [comment]
:+1: for react-rails/ react-source gem. Couple of good additions which could make the release.

**Comment by zpao** [comment]
Ok, calling this done. I'll followup on the tutorial
