### ISSUE TITLE
Ship 0.5.1

### ISSUE THREAD

**Issue by zpao** [facebook/react#439]
Unless 0.6 comes out really quickly, we'll have a 0.5.1.

Since It's likely we'll change master in non-trivial or breaking ways soon, I'm going to use this to track PRs and commits that should be merged into 0.5-stable
- [x] 893fba8373b648fa0a1370bcd3071250136dfad4 (#438)
- [x] 0d2d3360d0cf4eeacc388e625c91c72ccb8c4190
- [x] 0ef1ca00243671a0a969af68a173669fda0783b9
- [x] fbb741febbd14bb287e42f1c802a7538a82b9e9e
- [x] ac9dd922726b5e886cada4788cf43906f18aedf5 (#423)
- [x] 280eff41f351d3c73afd7a26b8b8811eaedde73d (#450)

**Explicitly not taking:**
- 58b3ae3136e959350ece18a753392ab23ab177b6 (changes behavior of default prop usage)
