### ISSUE TITLE
Umbrella 15.0

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#4600]
This is likely going to be a quick release after 0.14 goes out. Basically just a ~~"lightweight"~~ "garbage collection" release of 0.14.

Remove Deprecated Functionality

- [x] Remove getDOMNode / setProps / replaceProps monkey patching on DOM refs (@jimfb https://github.com/facebook/react/pull/5570)
- [x] Remove getDOMNode on createClass (@jimfb https://github.com/facebook/react/pull/5833)
- [x] Remove deprecated add-ons (such as cloneWithProps) (@jimfb - https://github.com/facebook/react/pull/5859)
- [x] Remove React.render and findDOMNode from the `react` package (@jimfb https://github.com/facebook/react/pull/5832)

Deprecated Functionality that Unlocks new Features
- [x] Remove Support for Inheritless Classes - Enables null return values in plain functions (#5355) (@jimfb https://github.com/facebook/react/pull/5884)

Spill over from 0.14:
- [ ] Make sure that the `react` package only includes "isomorphic" so that other renderers aren't burdened. Even if it is the same package, at least make sure that the module dependencies aren't burdened. Effectively make sure this is complete: Decouple dependencies between React DOM and React Isomorphic, except for currentOwner which React DOM still needs to set on React Isomorphic. (@sebmarkbage) See comment in #3866

Bonus:

- [ ] React Native ships its own copy of the renderer so that npm finally works properly.

**Comment by jimfb** [comment]
v15 has shipped.
