### ISSUE TITLE
Remove JSXTransformer, react-tools from website

### ISSUE THREAD

**Issue by zpao** [facebook/react#4677]
There are a few pieces in flight here so putting this together to track for my own sanity

- [x] Recommend Babel when we talk about transforming (#4546, already landed on `0.13-stable`)
- [ ] Remove our own use of JSXTransformer for transforming on site (#4131)
- [ ] Redirect jsx-compiler to babel repl (and remove our links to jsx-compiler)
- [ ] Update tutorial here and in tutorial repo (https://github.com/reactjs/react-tutorial/pull/71)
- [ ] Land all of this back on `0.13-stable` (#4675)
