### ISSUE TITLE
[New Docs] Docs Bugs & Issues

### ISSUE THREAD

**Issue by gaearon** [facebook/react#8035]
We just completely rewrote docs in #7864.
They're bound to cause some issues, have some mistakes, etc.
Let's keep this issue as an umbrella for all problems we're discovering after the initial rollout.
- [x] Old links shouldn't be 404! Major issue.
- [x] Topbar points to `https://facebook.github.io/react/index.html` which is ugly URL
- [x] We shouldn't use `Number` as an identifier https://github.com/facebook/react/issues/8034
- [x] Remove vars everywhere except ES5 page
- [x] JSX in depth has weird names like `Story1`, `render2` @lacker 
- [x] JSX in depth shows a failing example with `<hello>` tag but doesn't show how to fix it @lacker 
- [ ] Localized pages are gone: need to set up a new streamlined localization effort (cc @thejameskyle)
- [ ] Mention in default index.html that it is not production-ready
- [ ] Mark `mockComponent` as legacy and unnecessary 
https://github.com/facebook/react/issues/2499#issuecomment-94044857
- [ ] `shallowCompare` on Addons page should recommend `PureComponent` instead
- [ ] Figure out what to do with Community section (https://github.com/facebook/react/pull/6099)
- [ ] Mention string refs
- [x] Forms doc has mistakes
- [ ] Forms doc uses setState for uncontrolled components which is confusing
- [ ] Installation is messy

**Comment by luqmaan** [comment]
Docs on lifecycle methods are 404ing: https://facebook.github.io/react/docs/component-specs.html#updating-componentwillreceiveprops

**Comment by gaearon** [comment]
Yea, something happened to all redirects. @lacker

**Comment by gaearon** [comment]
@luqmaan Thanks, fixed. Let us know if you find more broken links.

**Comment by hzoo** [comment]
On Hello World, `https://facebook.github.io/docs/installation.html` should be `https://facebook.github.io/react/docs/installation.html` so the react/ isn't added and redirects to https://code.facebook.com/?

**Comment by johnbrett** [comment]
Great job on new docs all, love the live editor with error handling.

Just curious: Any reason why `var` is used on all the homepage tutorials? Curious whether there's a "best practice" on this.. would have thought `const` where possible, otherwise `let`?

**Comment by hzoo** [comment]
Another thing I noticed: this might of been an issue with the old docs but *syntax errors* don't have correct formatting of newlines from [babel-code-frame](https://github.com/babel/babel/tree/master/packages/babel-code-frame)

<img width="934" alt="screen shot 2016-10-21 at 5 45 35 pm" src="https://cloud.githubusercontent.com/assets/588473/19612730/4252bd54-97b6-11e6-9aff-bc61a9a53733.png">

Someone can make a pr to add to add `style={{whiteSpace: "pre-wrap"}}` as a style on the div at https://github.com/facebook/react/blob/eb118b70379ff01b30bb04dfce2c685c26d5453d/docs/_js/live_editor.js#L224 or edit the `.playgroundError` css class in https://github.com/facebook/react/blob/15-dev/docs/css/react.scss (`<pre>` seems to make it go over the width limit of the colored error box)

<img width="906" alt="screen shot 2016-10-21 at 5 47 37 pm" src="https://cloud.githubusercontent.com/assets/588473/19612770/7efe9db8-97b6-11e6-8fb5-d6f1ecc8f8c1.png">

Width would need to be longer to be accurate but it would be better than before

**Comment by gaearon** [comment]
>Any reason why var is used on all the homepage tutorials? 

No reason, feel free to send a PR fixing this.

**Comment by pythononwheels** [comment]
If this is the  "new style" I think you should point out the key differences to the "old style".
Just to take people with you.... knowing what key things change and why ...

**Comment by gaearon** [comment]
Does it matter at this point? It's not as much style as a lack of cohesion in previous docs.

They weren't really grouped by topic, there was no clear progression from simple to complex, their titles weren't descriptive, there were many random "tips" that didn't fit a cohesive narrative, they were using APIs that aren't used widely in the ecosystem anymore, etc.

New docs are in line with how people use React today, have descriptive titles, and a linear progression from simple to more complex topics.

That's the basic difference.

**Comment by p-adams** [comment]
Possible typo in docs: "Consider the ticking clock example from the one of the previous sections."

https://facebook.github.io/react/docs/state-and-lifecycle.html

**Comment by hnordt** [comment]
@gaearon the uncontrolled form example on https://facebook.github.io/react/docs/forms.html#uncontrolled-components is passing value, so it's actually a controlled example.

The correct example would be something like:

```jsx
class Form extends React.Component {
  constructor(props) {
    super(props);
    this.handleSubmit = this.handleSubmit.bind(this);
  }

  handleSubmit(event) {
    alert("Text field value is: '" + this.textInput.value + "'");
  }

  render() {
    return (
      <div>
        <input
          type="text"
          placeholder="Hello!"
          ref={(input) => this.textInput = input}
        />
        <button onClick={this.handleSubmit}>Submit</button>
      </div>
    );
  }
}

ReactDOM.render(<Form />, document.getElementById('root'));
```

**Comment by giuseppeg** [comment]
> A controlled component does not maintain its own internal state; the component renders purely based on props.

is a bit confusing, probably better clarify that we are talking about DOM state instead of React `state`.

**Comment by Andreyco** [comment]
Why was latest stable removed from landing page?

**Comment by gaearon** [comment]
@Andreyco What do you mean? There was a "Download Starter Kit" link that mentioned version but most people didn't find that "starter kit" useful. You can always find the latest version on Releases GH page.

**Comment by gaearon** [comment]
Another feedback on "Controlled Components": https://github.com/facebook/react/issues/8052

**Comment by Andreyco** [comment]
@gaearon Yes, I mean link that mentioned version. I don't care about link, I am interested in version information. Anyway, no big deal, I will search for latest in GH releases. TY.

**Comment by gaearon** [comment]
Merged a bunch of PRs with fixes. Keep them coming please!

**Comment by gaearon** [comment]
https://facebook.github.io/react/blog/2016/07/22/create-apps-with-no-configuration.html looks very weird on mobile, with some sort of a broken top bar

**Comment by gaearon** [comment]
Feedback on tutorial https://twitter.com/iandavey773/status/789870405389475840
cc @spicyj

**Comment by gaearon** [comment]
Figure out if we do redirects correctly https://twitter.com/spiceee/status/789774523549745152

**Comment by giuseppeg** [comment]
@gaearon have you considered to replace [redcarpet](https://github.com/vmg/redcarpet/issues/307) with [kramdown](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0)?

**Comment by gaearon** [comment]
@giuseppeg No idea, want to send a PR so I better understand the difference?

**Comment by gaearon** [comment]
More feedback: people are used to seeing version number on homepage. Can we add it somewhere and also link to the changelog for good measure?

**Comment by simonsmith** [comment]
Just reading though the "React Without ES6" page:

> In React components declared as ES6 classes, methods follow the same semantics as regular ES6 classes. This means that they don't automatically bind this to the instance. You'll have to explicitly use .bind(this) in the constructor:

Perhaps it's worth mentioning that this only applies in event handlers. Otherwise `this` works just fine.

**Comment by gaearon** [comment]
@simonsmith Sounds good.

**Comment by Aweary** [comment]
> Perhaps it's worth mentioning that this only applies in event handlers. Otherwise this works just fine. Happy to open a PR if so.

@simonsmith @gaearon I don't think that's true if I'm understanding you correctly. You need to bind your method anytime it might be executed in a context where `this` does not refer to the component instance it was defined on.

```js
class Bar extends React.Component {
  constructor(props) {
    super(props);
    // this will throw since it tries to access this.state.foo and
   // this.state is undefined on Bar
    this.props.logFoo();
  }
   render() {
  return <h1>Bar</h1>
  }

}

class Foo extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
    	foo: "foo"
    };
  }
  logFoo() {
    console.log("Foo is: ", this.state.foo);
  }
  render() {
    return <Bar logFoo={this.logFoo} />
  }
}
```

**Comment by gaearon** [comment]
The rule of thumb is that if you access method anywhere without `()` right after it, then you need to bind it.

**Comment by Aweary** [comment]
> The rule of thumb is that if you access method anywhere without () right after it, then you need to bind it.
Is that in the docs? If not, it should be 😄

**Comment by gaearon** [comment]
If it helps: https://twitter.com/dan_abramov/status/790612782471319553

**Comment by gaearon** [comment]
PRs welcome!

**Comment by simonsmith** [comment]
@Aweary Yeah, my point was the docs imply you need to use `bind` whenever you want to use an instance method which (as you've demonstrated) is only true some of the time.

I've seen code where every method was bound by hand even if it was just being called normally. I'll put together some changes and we can discuss in a PR 👍

**Comment by Shenlok** [comment]
No mention of the old string-based refs in the new docs. Should these be mentioned in a "deprecated" notice at least?

**Comment by gaearon** [comment]
@Shenlok They're technically not deprecated yet, just considered legacy.

[Refs and the DOM](https://facebook.github.io/react/docs/refs-and-the-dom.html) does mention them but too briefly:

>Using the ref callback just to set a property on the class is a common pattern for accessing DOM elements. If you are currently using `this.refs.myRefName` to access refs, we recommend using this pattern instead.

I agree we should add a small section at the bottom at least describing how string refs work, with a notice that we don't recommend using them. Could you send a PR for this?

**Comment by SMHFandA** [comment]
**Forms docs has mistakes.**
In "Forms" docs i found mistake in "Basic Radio Button" example. Method `render()` do not use `this.state.value`, but `state` has it. According "State and Lifecycle" docs it is bad:

> While this.props is set up by React itself and this.state has a special meaning, you are free to add additional fields to the class manually if you need to store something that is not used for the visual output.
If you don't use something in render(), it shouldn't be in the state.

**Comment by julen** [comment]
_(Sorry if this has been discussed elsewhere — I haven't been able to find any references to it though)._

> there were many random "tips" that didn't fit a cohesive narrative

I agree there was no narrative here, although at the same time many of these provided really good advice on anti-patterns and things to avoid. At least they have been very valuable to me on the way to learning React.

Now as I browse/search through the new docs, I am missing these and I am not sure whether they have been integrated under other sections or discarded by some reason. IMHO having a specific section on anti-patterns can be beneficial for newcomers to avoid making common mistakes (e.g. using props as initial state), as well as a reference to be able to point to others.

**Comment by gaearon** [comment]
@julen All valuable tips were integrated into the relevant content. There aren't many "antipatterns" in React despite what some people say. If something is "bad" we try to disallow it on the API level.

**Comment by jjcross** [comment]
Tiny (possible?) typo: in [reference-react.md](https://github.com/facebook/react/blob/new-docs/docs/docs/reference-react.md#reactchildrencount), the code for `React.Children.count` omits `React` which could be slightly confusing to newcomers.

**Comment by joni-** [comment]
I was wondering about the example code in https://facebook.github.io/react/docs/thinking-in-react.html#step-4-identify-where-your-state-should-live.

I don't really understand why the filtering should be ProductTable's responsibility. Wouldn't it make more sense to do the filtering in FilterableProductTable and just pass the filtered products down to ProductTable?

**Comment by kalmanh** [comment]
@gaearon @aweary I know I am "beating a dead horse" on this (as a similar issue was discussed above in this thread), but after reading the following in the docs in [handling events](https://facebook.github.io/react/docs/handling-events.html)

>You have to be careful about the meaning of this in JSX callbacks. In JavaScript, class methods are not bound by default. If you forget to bind this.handleClick and pass it to onClick, this will be undefined when the function is actually called.

>This is not React-specific behavior; it is a part of how functions work in JavaScript. 

you walk away thinking that you have to bind `hi()` and `callAnother()` methods in the following code

```javascript
class Test {
    constructor(){
        this.someProperty = "this is a test";
    }

    hi(){
     console.log(`this in hi() =  ${JSON.stringify(this)}`);
     this.callAnother();
    }

    callAnother(){
     console.log(`this in callAnother() = ${JSON.stringify(this)}`);
    }
}

const c = new Test();
c.hi();
```
which is obviously not true.

So, what the paragraph is really **trying** to say is [this](http://reactkungfu.com/2015/07/why-and-how-to-bind-methods-in-your-react-component-classes/), but it needs to do it better... :)

**Comment by gaearon** [comment]
@kalmanh Send a PR ;-)

**Comment by kkemple** [comment]
> Tiny (possible?) typo: in reference-react.md, the code for React.Children.count omits React which could be slightly confusing to newcomers.

@jayjaycross did you want to fix that typo? If not I'll create a PR

**Comment by jayjaycross** [comment]
@kkemple go for it!

**Comment by ivstas** [comment]
Not sure it is a proper place to post it, but "React documentation is Creative Commons licensed." in the end of `README.md` leads to **404 github page**.

**Comment by monkindey** [comment]
yeah, I think the licence-doc was removed by this commit https://github.com/facebook/react/pull/11137/commits/cfaa072ea052350960b98aaba7de1e39ab0ca5ce , maybe we can remove the `"React documentation is Creative Commons licensed."` section because of the migration of the document website.

**Comment by bvaughn** [comment]
The documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org). (For more info on why we made this move, see issue #11075.)

I've moved this issue to the new repo: reactjs/reactjs.org#84

Let's continue the discussion there!

**Comment by sag1v** [comment]
@bvaughn The `reactjs/reactjs.org` link is broken i think you meant `https://github.com/reactjs/reactjs.org/` ?
