### ISSUE TITLE
[Fiber] Error handling

### ISSUE THREAD

**Issue by gaearon** [facebook/react#8181]
Filing this as a todo list for myself.

- [x] #8210 After more scheduling tests are in place, add tests for uncaught errors in different roots
- [x] #8193 Remove recursion
- [ ] #8227 Choose and implement some sensible behavior for fataled roots (eg `visiblity: hidden`)
- [ ] #8212 Look at `batchedUpdates` (https://github.com/facebook/react/pull/8127#discussion_r86080646, https://github.com/facebook/react/pull/8127#issuecomment-257046617)

**Comment by sebmarkbage** [comment]
Do you want to add "Error handling when an error is thrown in detachRef callbacks" from the umbrella? Maybe we're happy with how it works already. However, I believe this case might be problematic: `return <ErrorBoundary><div ref={n => n.width} /><div ref={n => this.b = n} /></ErrorBoundary>;` since during unmount the first will throw, and the second won't be cleaned up.
