### ISSUE TITLE
Compiler Optimization Umbrella

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#9223]
Spinoff from https://github.com/reactjs/react-future/issues/50

I wanted to create an umbrella task for when we start working on compiler level optimizations. We've had [a tag](https://github.com/facebook/react/issues?q=is%3Aopen+is%3Aissue+label%3A%22Component%3A+Optimizing+Compiler%22) open for a while but these are fairly primitive optimizations. We want to be able to go further.

I don't think we'll start this project immediately but soon after the Fiber stuff is in place.

__Build Compiler Infra__

- [ ] Base-line cross-module full JavaScript AOT compiler.
- [ ] Compiler infra structure that fits well into existing tooling at FB, Webpack, Rollup based ecosystem etc. Support parallelism and incremental builds.

__Optimizations__

- [ ] Optimizing pure host/DOM elements ("string" components). Can be reasoned about at the core compiler level.
- [ ] Inlining pure functional components so that now the result can be reasoned about as a flat component.
- [ ] Basic constant folding for static configuration.
- [ ] Optimizing across component boundaries without inlining.
- [ ] Optimizing stateful functional components.

__Stretch Goals__

- [ ] Computing delta updates after code changes and lets Service Workers update based on that.

More to come...
