### ISSUE TITLE
Flat Bundle Followup Umbrella

### ISSUE THREAD

**Issue by gaearon** [facebook/react#9321]
Now that flat bundles are mostly done (https://github.com/facebook/react/pull/9327), separating out followup work into a separate issue.

- [x] Should `ReactDebugCurrentFrame` be in isomorphic package? https://github.com/facebook/react/pull/9365
- [x] Does `--extractErrors` fully work? It does update the file, but I'm still seeing "out of sync" console spam on rebuilds.
- [x] What happens if user forgets to envify `process.env.NODE_ENV` with webpack or use dead code elimination? Would it bundle both bundles? Sounds like even worse than what happens now. Would the user see any warnings?
- [x] Wrap CommonJS bundles into conditions https://github.com/facebook/react/issues/9361
- [x] Add a way to see bundle size change
- [x] Address internal FB `invariant` issue (I think they wanted it to be ignored so it's used verbatim)
- [x] Figure out RN rollout strategy
  - [x] When does it go 100% Fiber? Do we switch to flat bundles after that?
  - [x] See https://github.com/gaearon/react/commit/db1f7044d159d3ef2b29dbb7b42e9891a7d27cf4 for possible workaround for circular injection
  - [x] Flat ReactNative bundle would require flat React bundle but that's not what's shipped on npm
- [x] Make sure error codes transform still works
- [x] Add a fixture for ReactART
- [x] Make a final decision on how we bundle server renderer
- [x] Remove `providesModule` in source
- [x] Maybe reduce duplication between UMD bundles (e.g. put `object-assign` on React internals) https://github.com/facebook/react/pull/10671
- [x] Convert source to ES6 modules
- [x] Update release documentation
- [ ] <s>Extract shared state to npm package</s>
- [x] Use named imports in more places (eg event system)
- [x] Figure out a static injection mechanism for www and RN
- [ ] Investigate mangling and GCC optimizations
- [ ] Figure out how to share build process with third party renderers (e.g. ART for starters)
- [ ] Simplify the default build process to not run FB bundle builds, come up with a better strategy for FB only builds maybe?

**Comment by probablyup** [comment]
The bundle size analysis could be done in a [Dangerfile](https://github.com/danger/danger-js/blob/master/README.md). Jest uses the build job for a variety of arbitrary tasks like scanning for "use strict", for example.

**Comment by gaearon** [comment]
I think we've done everything planned here. GCC advanced is still not there but we have a separate issue tracking it. No plans to share build process with other renderers for now.

**Comment by blling** [comment]
What is GCC?

**Comment by gaearon** [comment]
Google Closure Compiler
